apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-flask-frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: hello-flask-frontend
  template:
    metadata:
      labels:
        app: hello-flask-frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: hello-flask-frontend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: hello-flask-frontend
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: http
