namespace: hello-flask

image: ghcr.io/mhan8796/hello-flask/hello-flask-frontend:d0c0db240bc3f4b53b48cad4458de4cc1a694b4a
replicas: 1
port: 80

backend:
  serviceName: hello-flask-backend
  servicePortName: http

ingress:
  enabled: true
  className: nginx
  host: ""
