namespace: hello-flask

image: ghcr.io/mhan8796/hello-flask/hello-flask-frontend:3ce64d577c5ef5e9f0d5a6c1d94fef257d75187b
replicas: 1
port: 80

backend:
  serviceName: hello-flask-backend
  servicePortName: http

ingress:
  enabled: true
  className: nginx
  host: ""
