apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-flask-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mhan8796/hello-flask.git
    targetRevision: main
    path: charts/hello-flask-backend
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-flask
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
